feat(indexer): Rollback if reorg
nervosnetwork/godwoken-web3 pull request #144
Opened 2022-01-17 06:45 UTC by classicalliu

2022-01-18 09:09 UTC, jjyr requested changes

2022-01-18 09:09 UTC, jjyr commented on crates/indexer/src/runner.rs
> +    pub async fn down_tip(&mut self) -> Result<()> {
revert_tip or rollback_tip

2022-01-18 09:09 UTC, jjyr commented on crates/indexer/src/runner.rs
> +    pub async fn down_tip(&mut self) -> Result<()> {
We can remove async from this function

2022-01-18 13:35 UTC, classicalliu commented on crates/indexer/src/runner.rs
> +    pub async fn down_tip(&mut self) -> Result<()> {
Updated

2022-01-25 03:02 UTC, jjyr approved these changes

2022-01-25 03:05 UTC, RetricSu approved these changes

2022-01-25 04:08 UTC, merged