fix(indexer): support compatible_chain_id for calculating eth_tx_hash
nervosnetwork/godwoken-web3 pull request #199
Opened 2022-03-08 10:33 UTC by RetricSu

https://github.com/nervosnetwork/godwoken-web3/issues/198

2022-03-08 14:24 UTC, Flouse approved these changes

2022-03-09 02:45 UTC, classicalliu requested changes

2022-03-09 02:45 UTC, classicalliu commented on packages/api-server/src/base/env-config.ts
> +}
```suggestion
export function calculateChainId(
  creatorId: number,
  compatibleChainId: number
): string {
  const chainId = BigInt(compatibleChainId) << 32n + BigInt(creatorId);
  console.log(
    `web3 chain_id: ${chainId}, calculating from compatible_chain_id: ${compatibleChainId}, creator_id: ${creatorId}`
  );
  return chainId.toString(10);
}
```

And we should avoid using snake_cake in typescript if not necessary

2022-03-09 03:58 UTC, classicalliu approved these changes

2022-03-09 06:58 UTC, Flouse approved these changes

2022-03-09 06:58 UTC, merged