docs: `transaction.to` MUST be a Contract Address
nervosnetwork/godwoken-web3 pull request #250
Opened 2022-04-01 09:58 UTC by Flouse

The `to` member of a Godwoken transaction must be a contract.

2022-04-02 01:59 UTC, RetricSu approved these changes

2022-04-04 10:20 UTC, Flouse commented on docs/compatibility.md
> +- **Transfer Value From EOA To EOA**: Use the `transfer function` in [CKB_ERC20_Proxy](https://github.com/nervosnetwork/godwoken-polyjuice/blob/3f1ad5b/solidity/erc20/README.md) contract [combined](h
```suggestion
- **Transfer Value From EOA To EOA**: Use the `transfer function` in [CKB_ERC20_Proxy](https://github.com/nervosnetwork/godwoken-polyjuice/blob/3f1ad5b/solidity/erc20/README.md) contract [combined](https://github.com/nervosnetwork/godwoken-polyjuice/blob/3f1ad5b322/solidity/erc20/SudtERC20Proxy_UserDefinedDecimals.sol#L154) with sUDT_ID = 1 (CKB a.k.a. [pCKB](https://github.com/nervosnetwork/godwoken/blob/develop/docs/life_of_a_polyjuice_transaction.md#pckb)).
```

2022-04-05 05:16 UTC, keroro520 requested changes

2022-04-05 05:16 UTC, keroro520 commented on docs/compatibility.md
> +- in the following RPCs, the transaction `to_address` parameter **CAN NOT** be an EOA address:
```suggestion
- In the following RPCs, the `to` parameter can only be a contract address and **CANNOT** be an EOA address:
```

2022-04-05 09:12 UTC, keroro520 approved these changes

2022-04-07 07:11 UTC, merged