chore: Update no system logs message
nervosnetwork/godwoken-web3 pull request #400
Opened 2022-06-16 04:26 UTC by classicalliu

For example: `Error: no system logs in tx_hash: 0x7a3de1cf7537520145b97292c0670dd8ba1118cd7be4e00f429a59959653e13d, block_number: 377, index: 4`

2022-06-16 04:29 UTC, Flouse approved these changes

2022-06-16 06:24 UTC, RetricSu approved these changes

2022-06-16 06:29 UTC, gpBlockchain approved these changes

2022-06-16 06:46 UTC, gpBlockchain requested changes

2022-06-16 06:46 UTC, gpBlockchain commented on crates/indexer/src/indexer.rs
> +                            let gw_tx_hash_hex = hex(gw_tx_hash.as_slice()).unwrap_or_else(|_| {
可不可以多做一步处理，能够看日志就能定位到问题，要不然我复现出来，还是需要你们这边再进一步分析，如果这个bug和历史多条交易或脏数据相关的话，仅凭这个信息定位起来也很麻烦。

2022-06-16 06:53 UTC, gpBlockchain commented
上次报这个错查到的信息
```
{"jsonrpc":"2.0","id":64,"result":{"raw":{"number":"0x248","parent_block_hash":"0x15148c34b23d636a185440fc9599846e52062b1102ba6400de37369008abbe4c","block_producer":"0x02000000140000002e9df163055245bfadd35e3a1f05f06096447c85","stake_cell_owner_lock_hash":"0x24842c3d28d9df39325ad05284efc3492972eec61606b51ded82369b3de72f04","timestamp":"0x1816164a9f4","prev_account":{"merkle_root":"0xcaae6839e22dd4f05c614c897117cb8aeab2bf640f0fd9d9e3ebc2887c5e61c1","count":"0x95"},"post_account":{"merkle_root":"0x13b0f81cc4a92111d57c77487dba7b10442aa5a9deb13785cc9f7b1a70e4ec7c","count":"0x9c"},"submit_transactions":{"tx_witness_root":"0x653a9fe94210d822d878ca2d89fea3d31a942dc7aeeed575667390dcece33129","tx_count":"0x8","prev_state_checkpoint":"0x862713721573e029a68be49492ceb67e2501ab783e715268a38ad78aba7cb952"},"submit_withdrawals":{"withdrawal_witness_root":"0x0000000000000000000000000000000000000000000000000000000000000000","withdrawal_count":"0x0"},"state_checkpoint_list":["0x1620be6a88cc13bcbb2e730e7e8175a58a3a986131f1ec6fea0383b21594413e","0x6a92fdce18ccbbecf9bd91397cb5b6507d3a50463b0d126ec8a0ff6955909b8e","0xccde53c59e7e45c3a7a4322d3769487ebee1d6d21bb1e2096d086236e609cce5","0xdef44e45528efe3410089761e0f888be7b7b23b8d1bf24e9253647b50dd513af","0x16112d8796e9b4c51d47484e5229b54778d043bad78a2e7d55c79384c07ae0bc","0xaf27fcfc0cf368f4f5f66a7f463198969c74899bf4ec9cf6ce6cfbd479d46c11","0x200e9a99d2802df45f864115fb97b26e7c460573dc961b0b7435f769f0ea6bbc","0x9a4873df88a9f9516a53c0619630feb499b86c3397f2b8517eb15475baf63951"]},"kv_state":[],"kv_state_proof":"0x","transactions":[{"raw":{"chain_id":"0x116e8","from_id":"0x5","to_id":"0x4","nonce":"0x10d","args":"0xffffff504f4c5903f63306000000000001000000000000000000000000000000000000000000000000000000000000001046000060806040523480156200001157600080fd5b50604051620000209062000084565b604051809103906000f0801580156200003d573d6000803e3d6000fd5b50600c60006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555062000092565b6107e18062003e2f83390190565b613d8d80620000a26000396000f3fe60806040526004361061023b5760003560e01c80638a13eea71161012e578063b153228c116100ab578063eaba91bb1161006f578063eaba91bb14610e42578063ee75c71d14610e80578063f19b495f14610e97578063f4eab45e14610eae578063fab077cf14610eef5761023b565b8063b153228c14610d56578063bb2fa29214610d6d578063cc59768f14610dfd578063d9801fc114610e14578063d9cb48a114610e2b5761023b565b8063a0f2f484116100f2578063a0f2f48414610b04578063a230446814610b1b578063a2acf48014610b63578063a3f6de9b14610b7a578063add494cc14610d3f5761023b565b80638a13eea714610a055780638c5176c814610a46578063930ef2ac14610a845780639c2be8db14610ad65780639e9b854114610aed5761023b565b806359c8a3c7116101bc5780636c8d5e03116101805780636c8d5e03146107195780636d84304a1461075a57806370dbed1e1461091f5780637de95cad1461094a5780637ed9ec8c146109da5761023b565b806359c8a3c7146106115780635db18cba146106285780636455cc9014610653578063675a6f88146106d757806368f381c2146107025761023b565b80632b6c3eab116102035780632b6c3eab1461051c5780633332c4a1146105475780634339a41b1461059657806349aa6aab146105ad57806354619637146105d85761023b565b80630e47e9f5146102405780630f35a82614610257578063139bf7591461032957806314dacd0d146103405780631ab6638c14610505575b600080fd5b34801561024c57600080fd5b50610255610f30565b005b34801561026357600080fd5b506103276004803603604081101561027a57600080fd5b810190808035906020019064010000000081111561029757600080fd5b8201836020820111156102a957600080fd5b803590602001918460208302840111640100000000831117156102cb57600080fd5b919080806020026020016040519081016040528093929190818152602001838360200280828437600081840152601f19601f820116905080830192505050505050509192919290803560ff169060200190929190505050611245565b005b34801561033557600080fd5b5061033e611288565b005b34801561034c57600080fd5b50610355611292565b6040518088815260200187815260200186815260200180602001806020018060200180602001858103855289818151815260200191508051906020019080838360005b838110156103b3578082015181840152602081019050610398565b50505050905090810190601f1680156103e05780820380516001836020036101000a031916815260200191505b50858103845288818151815260200191508051906020019080838360005b838110156104195780820151818401526020810190506103fe565b50505050905090810190601f1680156104465780820380516001836020036101000a031916815260200191505b50858103835287818151815260200191508051906020019060200280838360005b83811015610482578082015181840152602081019050610467565b50505050905001858103825286818151815260200191508051906020019080838360005b838110156104c15780820151818401526020810190506104a6565b50505050905090810190601f1680156104ee5780820380516001836020036101000a031916815260200191505b509b50505050505050505050505060405180910390f35b34801561051157600080fd5b5061051a6112bc565b005b34801561052857600080fd5b5061053161132a565b6040518082815260200191505060405180910390f35b34801561055357600080fd5b506105806004803603602081101561056a57600080fd5b8101908080359060200190929190505050611330565b6040518082815260200191505060405180910390f35b3480156105a257600080fd5b506105ab611354565b005b3480156105b957600080fd5b506105c2611391565b6040518082815260200191505060405180910390f35b3480156105e457600080fd5b506105ed6113c4565b60405180848152602001838152602001828152602001935050505060405180910390f35b34801561061d57600080fd5b50610626611764565b005b34801561063457600080fd5b5061063d611778565b6040518082815260200191505060405180910390f35b6106d56004803603606081101561066957600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050611822565b005b3480156106e357600080fd5b506106ec6119c3565b6040518082815260200191505060405180910390f35b34801561070e57600080fd5b506107176119c9565b005b34801561072557600080fd5b5061072e611bf0565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34801561076657600080fd5b5061076f611c16565b6040518088815260200187815260200186815260200180602001806020018060200180602001858103855289818151815260200191508051906020019080838360005b838110156107cd5780820151818401526020810190506107b2565b50505050905090810190601f1680156107fa5780820380516001836020036101000a031916815260200191505b50858103845288818151815260200191508051906020019080838360005b83811015610833578082015181840152602081019050610818565b50505050905090810190601f1680156108605780820380516001836020036101000a031916815260200191505b50858103835287818151815260200191508051906020019060200280838360005b8381101561089c578082015181840152602081019050610881565b50505050905001858103825286818151815260200191508051906020019080838360005b838110156108db5780820151818401526020810190506108c0565b50505050905090810190601f1680156109085780820380516001836020036101000a031916815260200191505b509b50505050505050505050505060405180910390f35b34801561092b57600080fd5b5061093461203f565b6040518082815260200191505060405180910390f35b34801561095657600080fd5b5061095f612045565b6040518080602001828103825283818151815260200191508051906020019080838360005b8381101561099f578082015181840152602081019050610984565b50505050905090810190601f1680156109cc5780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b3480156109e657600080fd5b506109ef6120e3565b6040518082815260200191505060405180910390f35b348015610a1157600080fd5b50610a1a6120e9565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b348015610a5257600080fd5b50610a8260048036036020811015610a6957600080fd5b81019080803560ff16906020019092919050505061210f565b005b348015610a9057600080fd5b50610ac060048036036020811015610aa757600080fd5b81019080803560ff1690602001909291905050506122ba565b6040518082815260200191505060405180910390f35b348015610ae257600080fd5b50610aeb61243b565b005b348015610af957600080fd5b50610b02612636565b005b348015610b1057600080fd5b50610b196127d1565b005b348015610b2757600080fd5b50610b306127db565b604051808381526020018273ffffffffffffffffffffffffffffffffffffffff1681526020019250505060405180910390f35b348015610b6f57600080fd5b50610b78612ae0565b005b348015610b865760 [...]

2022-06-20 09:27 UTC, gpBlockchain approved these changes

2022-06-20 09:51 UTC, merged

2022-06-20 11:01 UTC, gpBlockchain commented
可以提供相对于的kicker吗？

2022-06-20 11:05 UTC, RetricSu commented
> 可以提供相对于的kicker吗？

you can find the newest built image here(format: branchName-commitId),

- https://github.com/nervosnetwork/godwoken-web3/pkgs/container/godwoken-web3-indexer-prebuilds
- https://github.com/nervosnetwork/godwoken-web3/pkgs/container/godwoken-web3-prebuilds

 then you can change kicker's docker-compos image URL