feat: Support non eip155 tx
nervosnetwork/godwoken-web3 pull request #490
Opened 2022-08-15 03:34 UTC by classicalliu

Related:
- https://github.com/nervosnetwork/godwoken/pull/777

2022-08-15 05:39 UTC, keroro520 approved these changes

2022-08-15 05:39 UTC, keroro520 commented on packages/api-server/src/convert-tx.ts
> +  // if v = 27 || 28, set chain_id = 0
```suggestion
  // When `v = 27` and `v = 28`, the transaction is considered an non-eip155 transaction.
  //
  // Godwoken has a convention that non-eip155 transactions should be `tx.chain_id == 0`
```

2022-08-15 05:39 UTC, keroro520 commented on packages/api-server/src/convert-tx.ts
> +  const encoded: Buffer = rlp.encode(beforeEncode);
Creating standalone util functions to make it more readable would be helpful, such as `bool isEip155Transaction`, `bytes rlpEncodeEip155Transaction`, and `bytes rlpEncodeNonEip155Transaction`.

2022-08-15 05:39 UTC, keroro520 commented on packages/api-server/cli/fix-eth-tx-hash.ts
>    // v = chain_id * 2 + 35 + last byte of signature(0 / 1)
```suggestion
  // for non eip-155 txs(chain id != 0), v = chain_id * 2 + 35 + last byte of signature(0 / 1)
```

2022-08-15 06:50 UTC, RetricSu requested changes
please edit docs as well https://github.com/nervosnetwork/godwoken-web3/blob/main/docs/compatibility.md#2-signing-transaction-only-support-eip155

2022-08-16 06:54 UTC, classicalliu commented on packages/api-server/src/convert-tx.ts
> +  // if v = 27 || 28, set chain_id = 0
Updated

2022-08-16 06:54 UTC, classicalliu commented on packages/api-server/cli/fix-eth-tx-hash.ts
>    // v = chain_id * 2 + 35 + last byte of signature(0 / 1)
Updated

2022-08-16 06:54 UTC, classicalliu commented
> please edit docs as well https://github.com/nervosnetwork/godwoken-web3/blob/main/docs/compatibility.md#2-signing-transaction-only-support-eip155

Deleted

2022-08-16 11:41 UTC, RetricSu approved these changes

2022-08-22 03:28 UTC, merged