refactor: handling godwoken error
nervosnetwork/godwoken-web3 pull request #512
Opened 2022-08-31 06:36 UTC by keroro520

- Refactor handling of godwoken error
- Remove `error.data.failed_reason` and `error.data.message` from error JSONRPC response. See also: https://github.com/nervosnetwork/godwoken-web3/discussions/511
- Remove handling of [`Err("can't find backend for script_hash")`](https://github.com/nervosnetwork/godwoken-web3/blob/98e4dc1e44a6b4530910b428bf66898516752ae7/packages/api-server/src/methods/gw-error.ts#L257-L263)
- Remove `UNPREDICTABLE_GAS_LIMIT` prefix from error response of `eth_estimateGas`
- Revert https://github.com/nervosnetwork/godwoken-web3/pull/486, as Godwoken has fixed max cycle exceeded issue in https://github.com/nervosnetwork/godwoken/pull/728

2022-09-08 04:56 UTC, RetricSu commented on packages/api-server/src/cache/data.ts
> +  } else if (executionResult?.err != null) {
```suggestion
  }
  if (executionResult?.err != null) {
```
no need to use `else`?

2022-09-08 04:56 UTC, RetricSu commented on packages/api-server/src/methods/error.ts
> +    this.message = message;
seems already do `super(message);`?

2022-09-08 04:56 UTC, RetricSu commented on packages/api-server/src/methods/gw-error.ts
> +export function handleGwError(gwJsonrpcError: any) {
```suggestion
export function handleGwError(gwJsonRpcError: any) {
```

2022-09-08 04:56 UTC, RetricSu commented on packages/api-server/src/methods/modules/eth.ts
> +      } else if (isRpcError(error)) {
```sh
if (isGwError(error)) {
  handleGwError(error);
}

if (isRpcError(error)) {
  throw error;
}
```

2022-09-08 04:56 UTC, RetricSu commented on packages/api-server/src/methods/modules/eth.ts
> +      if (isGwError(error)) {
same above

2022-09-08 06:57 UTC, keroro520 commented
Updated:
- @RetricSu  All of your review suggestions have been applied at the new commit a7abecd5380d9c37b530548b8a880c7c88bea14f . Thanks

2022-09-08 07:35 UTC, RetricSu approved these changes

2022-09-08 07:48 UTC, classicalliu commented
Can hardhat parse error message after `error.data.message` removed ?

2022-09-08 08:57 UTC, keroro520 commented
> Can hardhat parse error message after `error.data.message` removed ?

 If HardHat fails after `error.data.message` removed, it would cause godwoken-tests fail. Am I right?

Godwoken-tests has several cases that trigger revert-error: https://github.com/nervosnetwork/godwoken-tests/pull/179/files
So my answer is YES.

2022-09-08 14:05 UTC, classicalliu commented
> > Can hardhat parse error message after `error.data.message` removed ?
> 
> If HardHat fails after `error.data.message` removed, it would cause godwoken-tests fail. Am I right?
> 
> Godwoken-tests has several cases that trigger revert-error: https://github.com/nervosnetwork/godwoken-tests/pull/179/files So my answer is YES.

Not sure, can you help to confirm this https://github.com/nervosnetwork/godwoken-web3/issues/423#issue-1292941376 @gpBlockchain ?

2022-09-08 17:04 UTC, Flouse requested changes

2022-09-09 03:22 UTC, keroro520 commented on packages/api-server/src/methods/gw-error.ts
> -    type: "SUDT_ERROR_INSUFFICIENT_BALANCE",
I have try to reproduce this error kind but failed:

Test code:
```js
describe("GW_SUDT_ERROR_INSUFFICIENT_BALANCE", function () {
  let rpc
  let owner
  let token
  before(async () => {
    const url = hardhat.network.config.url
    rpc = new RPC(url);

    [owner] = await ethers.getSigners();
    token = await hardhat.waffle.deployContract(owner, { abi: ERC20_ABI, bytecode: ERC20_BYTECODE }, ["pckb", "pCKB", 10000, 1, 18])
    await token.deployed();
    console.log("Token deployed to:", token.address);
  })

  it("Try to produce GW_SUDT_ERROR_INSUFFICIENT_BALANCE", async () => {
    [owner] = await ethers.getSigners();
  
    const transferTx = await token.transfer(owner.address, (20000000n * 10n**18n).toString());
    await transferTx.wait();
 })
});
```

Godwoken outputs:
```
Call gw rpc "gw_execute_raw_l2transaction" error: JSONRPCError: server error {"code":-32600,"message":"invalid exit code 2","data":{"tx_hash":"0xb01722a0fb57c226354d5392b39e236b4044c43c63f62d264795dc69436fc26f","block_number":"0x484","return_data":"0x","last_log":{"account_id":"0x46","service_flag":"0x2","data":"0x35610000000000003561000000000000000000000000000000000000000000000000000002000000"},"exit_code":"0x2"}}
```

Godwoken-Web3 v1.6.4 outputs:
```
{ code: -32099, message: 'UNPREDICTABLE_GAS_LIMIT: revert: ' }
```

This PR outputs:
```
{ code: -32000, message: 'execution reverted' }
```

2022-09-09 03:24 UTC, keroro520 commented on packages/api-server/src/methods/gw-error.ts
> -    type: "SUDT_ERROR_INSUFFICIENT_BALANCE",
It would be nice if someone could provide a testcase that produces the GW_SUDT_ERROR_INSUFFICIENT_BALANCE error.

2022-09-09 03:48 UTC, keroro520 commented on packages/api-server/src/methods/gw-error.ts
> -    type: "SUDT_ERROR_INSUFFICIENT_BALANCE",
I understand that we should wrap some common internal errors for users. This is definitely worth doing. But without test cases, the wrapper job seems blind. I propose that creates another tracking issue for the wrapper job and corresponding test cases? Please assign me if so.

2022-09-09 07:03 UTC, Flouse commented on packages/api-server/src/methods/gw-error.ts
> -    type: "SUDT_ERROR_INSUFFICIENT_BALANCE",
## Related test case
`ProviderError: UNPREDICTABLE_GAS_LIMIT: invalid argument 0: buildEthCallTx: from account ... -> insufficient balance, require 125000000012500000, got 0`
https://github.com/nervosnetwork/godwoken-tests/runs/8240249431?check_suite_focus=true#step:7:163

But it seems that the `insufficient balance` situation has been handled:
- https://github.com/nervosnetwork/godwoken-web3/blob/a7abecd5380d9c37b530548b8a880c7c88bea14f/packages/api-server/src/convert-tx.ts#L266
- https://github.com/nervosnetwork/godwoken-web3/blob/a7abecd5380d9c37b530548b8a880c7c88bea14f/packages/api-server/src/methods/validator.ts#L672

So, you are right, the special error wrapper job could be scheduled in another PR.

2022-09-09 07:04 UTC, Flouse approved these changes

2022-09-09 07:14 UTC, merged